---
- name: Generate Windows Service Status Report
  hosts: windows
  tasks:
    - name: Get Windows Service Status
      win_shell: Get-Service | Select-Object DisplayName,@{ n='Status'; e={ $_.Status.ToString() } } | ConvertTo-JSON
      register: service_output

    - name: Generate HTML Report
      template:
        src: service_status_template.j2
        dest: C:\Reports\report.html
      vars:
        services: "{{ service_output.stdout | from_json }}"
      ignore_errors: true
