---
- name: Generate Windows Service Status Report
  hosts: all
  tasks:
    - name: Get Windows Service Status
      win_shell: Get-Service | Select-Object DisplayName,Status
      register: service_output

    - name: Generate HTML Report
      template:
        src: service_status_template.j2
        dest: C:\Reports\report.html
      vars:
        services: "{{ service_output.stdout_lines }}"
